#!/usr/bin/env bash
set -e

README="$(cat README.md)"
README="${README//"$PREVIOUS_VERSION/ramda.min.js"/"$VERSION/ramda.min.js"}"
README="${README//"${PREVIOUS_VERSION%.*}/ramda.min.js"/"${VERSION%.*}/ramda.min.js"}"
echo "$README" >README.md
git add README.md

rm -f dist/ramda{,.min}.js
make dist/ramda{,.min}.js
git add dist/ramda{,.min}.js
