#!/usr/bin/env bash
set -e

README="$(cat README.md)"
README="${README//"$PREVIOUS_VERSION/ramda.min.js"/"$VERSION/ramda.min.js"}"
README="${README//"${PREVIOUS_VERSION%.*}/ramda.min.js"/"${VERSION%.*}/ramda.min.js"}"
echo "$README" >README.md
git add README.md

for filename in $(find src -maxdepth 1 -name "*.js" | xargs grep --files-without-match "@since v") ; do
  cp -- $filename{,.tmp}
  sed $'s/@memberOf R/@memberOf R\\\n * @since v'"$VERSION/" $filename.tmp >$filename
  rm -- $filename.tmp
  git add $filename
done

rm -f dist/ramda{,.min}.js
make dist/ramda{,.min}.js
git add dist/ramda{,.min}.js

npm run bookmarklet
git add BOOKMARKLET.md
